apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/phoqer/frontend:latest
        env:
        - name: NEXT_PUBLIC_BACK_URL
          value: https://api.phoqer.com
        ports:
        - containerPort: 3000
      imagePullSecrets:
       - name: ghcr-secret
