apiVersion: apps/v1
kind: Deployment
metadata:
  name: chats-app
  labels: 
    app: chats-app
    tier: frontend
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: chats-app
  template:
    metadata:
      labels:
        app: chats-app
    spec:
      containers:
      - name: chats-app
        image: ghcr.io/phoqer/chats-app:latest
        ports: 
        - containerPort: 4004
      imagePullSecrets:
       - name: ghcr-secret
