version: '3.7'

services:
  web:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    command: gunicorn share.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - web
