version: '3.7'

services:
  backend:
    container_name: backend
    image: "${BACKEND_IMAGE}"
    command: uvicorn main:app --root-path /api/v2 --reload --workers 1 --host 0.0.0.0 --port 8001
    volumes:
      - media_volume:/phoqer/FastAPI/mediafiles/
    expose:
      - 8001
    env_file: .env
  frontend:
    container_name: frontend
    image: "${FRONTEND_IMAGE}"
    command: yarn run start
    stdin_open: true
    tty: true
    expose:
      - 4000
    environment:
      - HOST=0.0.0.0
    env_file: .env
    depends_on:
      - backend
  db:
    container_name: db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file: .env
    volumes:
      - pgadmin:/root/.pgadmin
    expose:
      - 5050
    restart: unless-stopped
  nginx:
    container_name: nginx
    image: "${NGINX_IMAGE}"
    restart: unless-stopped
    volumes:
      - media_volume:/phoqer/FastAPI/mediafiles
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot/
    ports:
      - 80:80
      - 443:443
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    depends_on:
      - backend
      - frontend
      - pgadmin
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

volumes:
  postgres_data:
  media_volume:
  pgadmin: