version: '3.7'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/home/phoqer/backend/staticfiles/
      - ./backend/:/home/phoqer/backend/
      - media_volume:/home/phoqer/backend/mediafiles/
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  fastapi:
    container_name: FastAPI
    build:
      context: ./FastAPI
      dockerfile: build/Dockerfile
    command: uvicorn main:app --root-path /api/v2 --reload --workers 1 --host 0.0.0.0 --port 8001
    expose:
      - 8001
    env_file:
      - ./.env.dev
    depends_on:
      - backend
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - 4000
    env_file:
      - ./.env.dev
    depends_on:
      - backend
  db:
    container_name: db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
      - ./.env.dev
    volumes:
      - pgadmin:/root/.pgadmin
    expose:
      - 5050
    restart: unless-stopped
  nginx:
    container_name: nginx
    build: ./nginx
    volumes:
      - static_volume:/home/phoqer/backend/staticfiles/
      - media_volume:/home/phoqer/backend/mediafiles/
    ports:
      - 80:80
    depends_on:
      - backend
      - fastapi
      - frontend
      - pgadmin

volumes:
  postgres_data:
  static_volume:
  media_volume:
  pgadmin: