version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/home/share/backend/staticfiles/
      - ./backend/:/home/share/backend/
      - media_volume:/home/share/backend/mediafiles/
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    expose:
      - 4000
    env_file:
      - ./.env.dev
    depends_on:
      - backend
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/share/backend/staticfiles/
      - media_volume:/home/share/backend/mediafiles/
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_volume:
  media_volume: