version: '3.7'

services:
  backend:
    container_name: backend
    image: "${BACKEND_IMAGE}"
    command: uvicorn main:app --root-path /api/v2 --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file: .env
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    container_name: frontend
    image: "${FRONTEND_IMAGE}"
    command: yarn start
    env_file: .env
    restart: unless-stopped
    depends_on:
      - backend
    ports:
      - "4000:4000"

  db:
    container_name: db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file: .env
    volumes:
      - pgadmin:/root/.pgadmin
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "5050:5050"

volumes:
  postgres_data:
  pgadmin: