version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      cache_from:
        - "${BACKEND_IMAGE}"
    image: "${BACKEND_IMAGE}"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/home/phoqer/backend/staticfiles/
      - media_volume:/home/phoqer/backend/mediafiles/
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      cache_from:
        - "${FRONTEND_IMAGE}"
    image: "${FRONTEND_IMAGE}"
    expose:
      - 4000
    env_file:
      - ./.env.dev
    depends_on:
      - backend
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
  nginx:
    build:
      context: ./nginx
      cache_from:
        - "${NGINX_IMAGE}"
    image: "${NGINX_IMAGE}"
    volumes:
      - static_volume:/home/phoqer/backend/staticfiles/
      - media_volume:/home/phoqer/backend/mediafiles/
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

volumes:
  postgres_data:
  static_volume:
  media_volume: