version: '3.7'

services:
  backend :
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/home/share/backend/staticfiles/
      - ./backend/:/home/share/backend/
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/share/backend/staticfiles/
    ports:
      - 1337:80
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume: