version: '3.7'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      cache_from:
        - "${BACKEND_IMAGE}"
    image: "${BACKEND_IMAGE}"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - media_volume:/home/phoqer/mediafiles/
    expose:
      - 8000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  fastapi:
    container_name: FastAPI
    build:
      context: ./FastAPI
      dockerfile: build/Dockerfile
      cache_from:
        - "${FASTAPI_IMAGE}"
    image: "${FASTAPI_IMAGE}"
    command: uvicorn main:app --root-path /api/v2 --reload --workers 1 --host 0.0.0.0 --port 8001
    expose:
      - 8001
    env_file:
      - ./.env.dev
    depends_on:
      - backend
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      cache_from:
        - "${FRONTEND_IMAGE}"
    image: "${FRONTEND_IMAGE}"
    expose:
      - 4000
    env_file:
      - ./.env.dev
    depends_on:
      - backend
  db:
    container_name: db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev
  nginx:
    container_name: nginx
    build:
      context: ./nginx
      cache_from:
        - "${NGINX_IMAGE}"
    image: "${NGINX_IMAGE}"
    volumes:
      - media_volume:/home/phoqer/mediafiles/
    ports:
      - 80:80
    depends_on:
      - backend
      - fastapi
      - frontend

volumes:
  postgres_data:
  media_volume: