version: '3.7'

services:
  backend:
    container_name: backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      cache_from:
        - "${BACKEND_IMAGE}"
    image: "${BACKEND_IMAGE}"
    command: uvicorn main:app --root-path /api/v2 --reload --workers 1 --host 0.0.0.0 --port 8000
    env_file: .env

  frontend:
    container_name: frontend
    build:
      args:
        NEXT_PUBLIC_URL: ${NEXT_PUBLIC_URL}
        NEXT_PUBLIC_WS: ${NEXT_PUBLIC_WS}
      context: ./frontend
      dockerfile: Dockerfile
      cache_from:
        - "${FRONTEND_IMAGE}"
    image: "${FRONTEND_IMAGE}"
    command: yarn start
    env_file: .env
    depends_on:
      - backend

  db:
    container_name: db
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: .env

volumes:
  postgres_data: