version: '3.7'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      cache_from:
        - "${BACKEND_IMAGE}"
    image: "${BACKEND_IMAGE}"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - static_volume:/home/share/backend/staticfiles/
      - media_volume:/home/share/backend/mediafiles/
    expose:
      - 8000
    env_file:
      - ./.env.dev
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      cache_from:
        - "${FRONTEND_IMAGE}"
    image: "${FRONTEND_IMAGE}"
    expose:
      - 4000
    env_file:
      - ./.env.dev
    depends_on:
      - backend
  nginx:
    build:
      context: ./nginx
      cache_from:
        - "${NGINX_IMAGE}"
    image: "${NGINX_IMAGE}"
    volumes:
      - static_volume:/home/share/backend/staticfiles/
      - media_volume:/home/share/backend/mediafiles/
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend

volumes:
  static_volume:
  media_volume: