version: '3.7'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: Dockerfile
      cache_from:
        - "${BACKEND_IMAGE}"
    image: "${BACKEND_IMAGE}"
    command: python main.py
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
    depends_on:
      - db

  db:
    container_name: db
    image: postgres:12.0-alpine
    environment:
      - POSTGRES_USER=phoqer
      - POSTGRES_DB=phoqer_dev
      - POSTGRES_PASSWORD=apple-b@nana-f1re
