apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-poc
  labels: 
    app: backend-poc
    tier: backend
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: backend-poc
  template:
    metadata:
      labels:
        app: backend-poc
    spec:
      containers:
      - name: backend-poc
        image: ghcr.io/phoqer/backend-poc:latest
        ports: 
        - containerPort: 8000
      imagePullSecrets:
       - name: ghcr-secret
