apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels: 
    app: api-gateway
    tier: backend
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: ghcr.io/phoqer/api-gateway:latest
        ports: 
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: env-configmap
        - secretRef:
            name: env-secrets
      imagePullSecrets:
       - name: ghcr-secret
