name: Lint and Test BE

on:
  push:
    paths:
      - "**/*.py"

jobs:
  backend_lint_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: x64
      - name: Checkout Phoqer
        uses: actions/checkout@v2
      - name: Add environment variables to .env
        run: |
          echo BACKEND_IMAGE=${{ secrets.BACKEND_IMAGE }} >> .env
          echo FERNET_SECRET_KEY=${{ secrets.FERNET_SECRET_KEY }} >> .env
          echo IAM_SES_USER_ACCESS_KEY=${{ secrets.IAM_SES_USER_ACCESS_KEY }} >> .env
          echo IAM_SES_USER_SECRET_KEY=${{ secrets.IAM_SES_USER_SECRET_KEY }} >> .env
      - name: Log in to GitHub Packages
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
      - name: Pull existing image for cache
        run: |
          docker pull ${{ secrets.BACKEND_IMAGE }} || true
      - name: Build images
        run: docker-compose -f docker-compose.yml --env-file .env up --build -d
      - name: Run lint
        run: docker-compose -f docker-compose.yml exec -T backend ./lint.sh
      - name: Run tests
        run: docker-compose -f docker-compose.yml exec -T backend pytest -vv
