name: Lint and Test BE

on:
  push:
    paths:
      - "**/*.py"

jobs:
  backend_lint_and_test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: x64
      - name: Checkout Phoqer
        uses: actions/checkout@v2
      - name: Log in to GitHub Packages
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${GITHUB_ACTOR} --password-stdin docker.pkg.github.com
      - name: Pull existing image for cache
        run: docker pull ${{ secrets.BACKEND_IMAGE }} || true
      - name: Build images
        run: |
          docker-compose \
          -f docker-compose.test-backend.yml \
          -e BACKEND_IMAGE=${{ secrets.BACKEND_IMAGE }} \
          up --build -d
      - name: Run lint
        run: docker-compose -f docker-compose.test-backend.yml exec backend ./lint.sh
      - name: Run tests
        run: docker-compose -f docker-compose.test-backend.yml exec backend pytest -vv