name: Lint

on:
  push:
    paths:
      - "**/*.py"

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9.1
          architecture: x64
      - name: Checkout Phoqer
        uses: actions/checkout@v2
      - name: Install flake8 and plugins
        run: pip install flake8 flake8-pytest-style
      - name: Run flake8
        run: flake8
        working-directory: ./backend
