name: Lint BE

on:
  push:
    paths:
      - "**/*.py"

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: x64
      - name: Checkout Phoqer
        uses: actions/checkout@v2
      - name: Install requirements
        run: pip install -r build/requirements.txt
      - name: Run lint.sh
        run: ./lint.sh
        working-directory: ./backend
