name: Lint BE

on:
  push:
    paths:
      - "**/*.py"

jobs:
  python_lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: x64
      - name: Checkout Phoqer
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r build/requirements.txt
      - name: Run lint.sh
        run: ./lint.sh
