name: Pytest

on:
  push:
    paths:
      - "**/*.py"

jobs:
  pytest:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./backend
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.8.7
          architecture: x64
      - name: Checkout Phoqer
        uses: actions/checkout@v2
      - name: Install pytest and plugins
        run: pip install -r requirements.txt
      - name: Run pytest
        run: pytest
